### PR TITLE
update to add color theory to html

### PR DESCRIPTION
**Pull request by cpestana**
updates to index.html with color theory content

### CODE REVIEW

**Review by gina-noel — COMMENTED** [review]
Looks great with me, although Ted is probably the best reviewer since he is doing the CSS :)

**Review by ghost — COMMENTED** [review]
it looks good, is the color from error or

**Comment by cpestana** [comment]
Hello Emmy, the red is what is being deleted. It is not an error.

**Comment by cpestana** [comment]
Style sheet was added and created conflict. Created another branch to update HTML. Closing this one.

**Pull request closed without merging**
